//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSS_DEMO.MssService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MssService.CourseraApiSoap")]
    public interface CourseraApiSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetScheduledSubject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetScheduledSubject(string authenKey, string teacher, string[] lsSubjects, string semester);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetScheduledSubject", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetScheduledSubjectAsync(string authenKey, string teacher, string[] lsSubjects, string semester);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStudents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getStudents(string authenKey, string teacher, string subjectCode, string className, string semester);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStudents", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getStudentsAsync(string authenKey, string teacher, string subjectCode, string className, string semester);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CourseraApiSoapChannel : MSS_DEMO.MssService.CourseraApiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CourseraApiSoapClient : System.ServiceModel.ClientBase<MSS_DEMO.MssService.CourseraApiSoap>, MSS_DEMO.MssService.CourseraApiSoap {
        
        public CourseraApiSoapClient() {
        }
        
        public CourseraApiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CourseraApiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseraApiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseraApiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetScheduledSubject(string authenKey, string teacher, string[] lsSubjects, string semester) {
            return base.Channel.GetScheduledSubject(authenKey, teacher, lsSubjects, semester);
        }
        
        public System.Threading.Tasks.Task<string> GetScheduledSubjectAsync(string authenKey, string teacher, string[] lsSubjects, string semester) {
            return base.Channel.GetScheduledSubjectAsync(authenKey, teacher, lsSubjects, semester);
        }
        
        public string getStudents(string authenKey, string teacher, string subjectCode, string className, string semester) {
            return base.Channel.getStudents(authenKey, teacher, subjectCode, className, semester);
        }
        
        public System.Threading.Tasks.Task<string> getStudentsAsync(string authenKey, string teacher, string subjectCode, string className, string semester) {
            return base.Channel.getStudentsAsync(authenKey, teacher, subjectCode, className, semester);
        }
    }
}
