//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSS_DEMO.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.MSSWSSoap")]
    public interface MSSWSSoap {
        
        // CODEGEN: Generating message contract since element name userLogin from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getScheduledSubject", ReplyAction="*")]
        MSS_DEMO.ServiceReference.getScheduledSubjectResponse getScheduledSubject(MSS_DEMO.ServiceReference.getScheduledSubjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getScheduledSubject", ReplyAction="*")]
        System.Threading.Tasks.Task<MSS_DEMO.ServiceReference.getScheduledSubjectResponse> getScheduledSubjectAsync(MSS_DEMO.ServiceReference.getScheduledSubjectRequest request);
        
        // CODEGEN: Generating message contract since element name userLogin from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStudents", ReplyAction="*")]
        MSS_DEMO.ServiceReference.getStudentsResponse getStudents(MSS_DEMO.ServiceReference.getStudentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStudents", ReplyAction="*")]
        System.Threading.Tasks.Task<MSS_DEMO.ServiceReference.getStudentsResponse> getStudentsAsync(MSS_DEMO.ServiceReference.getStudentsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getScheduledSubjectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getScheduledSubject", Namespace="http://tempuri.org/", Order=0)]
        public MSS_DEMO.ServiceReference.getScheduledSubjectRequestBody Body;
        
        public getScheduledSubjectRequest() {
        }
        
        public getScheduledSubjectRequest(MSS_DEMO.ServiceReference.getScheduledSubjectRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getScheduledSubjectRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public MSS_DEMO.ServiceReference.ArrayOfString listSubject;
        
        public getScheduledSubjectRequestBody() {
        }
        
        public getScheduledSubjectRequestBody(string userLogin, MSS_DEMO.ServiceReference.ArrayOfString listSubject) {
            this.userLogin = userLogin;
            this.listSubject = listSubject;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getScheduledSubjectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getScheduledSubjectResponse", Namespace="http://tempuri.org/", Order=0)]
        public MSS_DEMO.ServiceReference.getScheduledSubjectResponseBody Body;
        
        public getScheduledSubjectResponse() {
        }
        
        public getScheduledSubjectResponse(MSS_DEMO.ServiceReference.getScheduledSubjectResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getScheduledSubjectResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getScheduledSubjectResult;
        
        public getScheduledSubjectResponseBody() {
        }
        
        public getScheduledSubjectResponseBody(string getScheduledSubjectResult) {
            this.getScheduledSubjectResult = getScheduledSubjectResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStudentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStudents", Namespace="http://tempuri.org/", Order=0)]
        public MSS_DEMO.ServiceReference.getStudentsRequestBody Body;
        
        public getStudentsRequest() {
        }
        
        public getStudentsRequest(MSS_DEMO.ServiceReference.getStudentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getStudentsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userLogin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string classID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string subjectID;
        
        public getStudentsRequestBody() {
        }
        
        public getStudentsRequestBody(string userLogin, string classID, string subjectID) {
            this.userLogin = userLogin;
            this.classID = classID;
            this.subjectID = subjectID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStudentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStudentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public MSS_DEMO.ServiceReference.getStudentsResponseBody Body;
        
        public getStudentsResponse() {
        }
        
        public getStudentsResponse(MSS_DEMO.ServiceReference.getStudentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getStudentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getStudentsResult;
        
        public getStudentsResponseBody() {
        }
        
        public getStudentsResponseBody(string getStudentsResult) {
            this.getStudentsResult = getStudentsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MSSWSSoapChannel : MSS_DEMO.ServiceReference.MSSWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MSSWSSoapClient : System.ServiceModel.ClientBase<MSS_DEMO.ServiceReference.MSSWSSoap>, MSS_DEMO.ServiceReference.MSSWSSoap {
        
        public MSSWSSoapClient() {
        }
        
        public MSSWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MSSWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MSSWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MSSWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MSS_DEMO.ServiceReference.getScheduledSubjectResponse MSS_DEMO.ServiceReference.MSSWSSoap.getScheduledSubject(MSS_DEMO.ServiceReference.getScheduledSubjectRequest request) {
            return base.Channel.getScheduledSubject(request);
        }
        
        public string getScheduledSubject(string userLogin, MSS_DEMO.ServiceReference.ArrayOfString listSubject) {
            MSS_DEMO.ServiceReference.getScheduledSubjectRequest inValue = new MSS_DEMO.ServiceReference.getScheduledSubjectRequest();
            inValue.Body = new MSS_DEMO.ServiceReference.getScheduledSubjectRequestBody();
            inValue.Body.userLogin = userLogin;
            inValue.Body.listSubject = listSubject;
            MSS_DEMO.ServiceReference.getScheduledSubjectResponse retVal = ((MSS_DEMO.ServiceReference.MSSWSSoap)(this)).getScheduledSubject(inValue);
            return retVal.Body.getScheduledSubjectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MSS_DEMO.ServiceReference.getScheduledSubjectResponse> MSS_DEMO.ServiceReference.MSSWSSoap.getScheduledSubjectAsync(MSS_DEMO.ServiceReference.getScheduledSubjectRequest request) {
            return base.Channel.getScheduledSubjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<MSS_DEMO.ServiceReference.getScheduledSubjectResponse> getScheduledSubjectAsync(string userLogin, MSS_DEMO.ServiceReference.ArrayOfString listSubject) {
            MSS_DEMO.ServiceReference.getScheduledSubjectRequest inValue = new MSS_DEMO.ServiceReference.getScheduledSubjectRequest();
            inValue.Body = new MSS_DEMO.ServiceReference.getScheduledSubjectRequestBody();
            inValue.Body.userLogin = userLogin;
            inValue.Body.listSubject = listSubject;
            return ((MSS_DEMO.ServiceReference.MSSWSSoap)(this)).getScheduledSubjectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MSS_DEMO.ServiceReference.getStudentsResponse MSS_DEMO.ServiceReference.MSSWSSoap.getStudents(MSS_DEMO.ServiceReference.getStudentsRequest request) {
            return base.Channel.getStudents(request);
        }
        
        public string getStudents(string userLogin, string classID, string subjectID) {
            MSS_DEMO.ServiceReference.getStudentsRequest inValue = new MSS_DEMO.ServiceReference.getStudentsRequest();
            inValue.Body = new MSS_DEMO.ServiceReference.getStudentsRequestBody();
            inValue.Body.userLogin = userLogin;
            inValue.Body.classID = classID;
            inValue.Body.subjectID = subjectID;
            MSS_DEMO.ServiceReference.getStudentsResponse retVal = ((MSS_DEMO.ServiceReference.MSSWSSoap)(this)).getStudents(inValue);
            return retVal.Body.getStudentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MSS_DEMO.ServiceReference.getStudentsResponse> MSS_DEMO.ServiceReference.MSSWSSoap.getStudentsAsync(MSS_DEMO.ServiceReference.getStudentsRequest request) {
            return base.Channel.getStudentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MSS_DEMO.ServiceReference.getStudentsResponse> getStudentsAsync(string userLogin, string classID, string subjectID) {
            MSS_DEMO.ServiceReference.getStudentsRequest inValue = new MSS_DEMO.ServiceReference.getStudentsRequest();
            inValue.Body = new MSS_DEMO.ServiceReference.getStudentsRequestBody();
            inValue.Body.userLogin = userLogin;
            inValue.Body.classID = classID;
            inValue.Body.subjectID = subjectID;
            return ((MSS_DEMO.ServiceReference.MSSWSSoap)(this)).getStudentsAsync(inValue);
        }
    }
}
