//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSS_DEMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Deadline
    {
        public string Semester_ID { get; set; }
        public string Course_ID { get; set; }
        public int Course_Deadline_ID { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Semester Semester { get; set; }
    }
}
