//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSS_DEMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Role
    {
        public int User_ID { get; set; }
        public int Role_ID { get; set; }
        public string Login { get; set; }
        public bool isActive { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
